### ISSUE TITLE
 Will this image work on armv7 platform?

### ISSUE THREAD

**Issue by vsterian** [ukewea/python-talib#2]
Will this image work on armv7 platform?

**Comment by ukewea** [comment]
From what I can recall, I've encountered series of compilation issues when building the armv7 variant. Those issues might be solved now, but at that time I decided to drop 32bit architectures (x86/armv7) support altogether.

You could fork the repo and modify the Dockerfile or GitHub Action workflow and try that out!

Thanks.

**Comment by ukewea** [comment]
Oops, I just found there's actually a arm build variant on Docker Hub...
Did you get any warning or error when trying the container image?

**Comment by vsterian** [comment]
Hey! Sorry for late reply.

Not yet, I haven't tried building the docker image. I'll use a variant of base image for armv7 and I'll let you know.

I was wondering whether the talib build will actually work using your method as I tried various ways and couldn't get it working. 

Your repo caught my attention since it's saying in the description that will work on armv7 but since I haven't seen any further reference in the actual repo documentation I wanted to ask beforehand 

LE: can you please reference the docker image that you were mentioning in your second comment?

Thanks
Vlad

**Comment by ukewea** [comment]
Hi Vlad,

You can try older images on https://hub.docker.com/r/wuuker/python-talib/tags, which I'm also the maintainer.

Images on Docker Hub is built from a Dockerfile which is almost identical to the one in this repo, the main differences are:
* images on Docker Hub is based on Ubuntu 22.04, which comes with Python 3.10, no pre-built virtual environment.
* images on GHCR is based on Ubuntu 23.10, which comes with Python 3.11, with a pre-built virtual environment.

You could try the tutorial below on your armv7 devices to test if the image on Docker Hub works before you go further, **just follow all steps except step 2** (step 2 is not necessary for images with Python 3.10)

Thanks.

----------------

## Step 1: Start Your Docker Container with Automatic Cleanup
To begin, start your Docker container using the docker run command with the `--rm` flag. This ensures that the container is automatically removed after you're done, keeping your system clean. Run the following command in your terminal:

```bash
docker run -it --rm --name talib_test wuuker/python-talib:latest /bin/bash
```

This command will create and start a new container instance from the `wuuker/python-talib:latest` image, open an interactive terminal session inside the container, and automatically clean up the container when you exit the shell.

## Step 2: Activate the Python Virtual Environment
Once inside the container's shell, activate the Python virtual environment to use the Python version and libraries (including TA-Lib) installed within it:

```bash
source /ctr-py-venv/bin/activate
```

## Step 3: Start an Interactive Python Session
With the virtual environment activated, start an interactive Python session by typing python and pressing Enter:

```bash
python
```

## Step 4: Test TA-Lib Functionality
Now, you're ready to test TA-Lib. Let's perform a simple operation to calculate a moving average from an array of closing prices.

```python
import talib
import numpy as np
close_prices = np.array([4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])
sma = talib.SMA(close_prices, timeperiod=5)
print(sma)
```

## Step 5: Review the Expected Output
After running the above commands, you should see the following output in your terminal:

```
[nan nan nan nan 4.2 4.3 4.4 4.5 4.6 4.7]
```

This output shows the calculated 5-day simple moving average for the provided array of closing prices. The nan values represent the lack of enough data points (less than 5) to calculate the average for the first four entries.

## Step 6: Exit the Python Shell and Container
To exit the Python interactive shell, type exit() or press Ctrl+D. To exit the container's bash shell, simply type exit again.

```
exit()  # Exits the Python shell
exit    # Exits the container shell
```

By following these steps, you've successfully tested the functionality of TA-Lib inside your Docker container using an interactive Python session, and the container will be cleaned up automatically thanks to the `--rm` flag used when starting the container.

**Comment by ukewea** [comment]
By the way, There's no armv7 on GHCR, perhaps the build environment.. I use QEMU to build arm variants pushed to GHCR while I used a Raspberry Pi 3 to build the same image pushed to Docker Hub)

I have no armv7 devices on my hand for now, so you might have to do it on your own if you want to build a image whichs runs Python 3.11.

**Comment by vsterian** [comment]
Yeah, let's take the problems one by one. I would first give it a go building it locally and then move to the GHCR.

So basically I would need to use the "arm" version from https://hub.docker.com/r/wuuker/python-talib/tags ? Would this work with armv7?

**Comment by ukewea** [comment]
Yep, I've tested it with a Raspberry Pi2 a while ago.
For some reason it shows as "arm", but it will work with armv7.

**Comment by ukewea** [comment]
Ahh... just found something weired
* `arm` variant is based on Ubuntu 22.10
* `amr64/v8` and `amd64` variants are based on Ubuntu 23.10 (!

I have no idea why it goes this way (it should be all based on either 22.10 or 23.10), but shouldn't be too much of an issue I guess.

**Comment by ukewea** [comment]
I looked to the history of this repo, on GitLab, which is responsible for building the image on Docker Hub, and I found a comment I just made:

```
failed since migrate to Python3.11 & Ubuntu 23.10, so remove the support for ARM 32 bit
```

So, to recap:
- Docker Hub is the place where I initially published the image, images were originally based on Ubuntu 22.10
- I encountered issue building image based on Ubuntu 23.10 with arm/v7, so I removed the build step of arm/v7 variant in GitLab CI/CD

That's why on Docker Hub we see arm64 & amd64 variants run on Ubuntu 23.10 while arm/v7 runs on Ubuntu 22.10

So, you might want to downgrade base image to Ubuntu 22.10 if you can't build image with Ubuntu 23.10 as base.

**Comment by ukewea** [comment]
No reply for 7 days, close the issue

**Comment by vsterian** [comment]
Hey,

Sorry for the late reply. I was actually testing a lot of stuff using your images. So far I think it works as expected when pulling the images from docker hub.

However, I'm not able to build one of my own images using the dockerfile from this repo ( for now I have postponed this action)

Now, since I have some python packages ( alongside talib and numpy), like cryptography and tensorflow which are not available "as-is" for raspberry pi, I have been struggling to find a way of installing them beforehand in my dockerfile.
While I have managed to successfully install cryptography on your image with "latest" tag, which is using python3.11, I am unable to find a compatible .whl for tensorflow that would work with 3.11 . The only one that I was able to find is one that is compatible with python3.8 .

Is there any chance maybe to build an image ( using the base image from latest) but use python 3.8 instead of 3.11? Is this feasible considering the talib installation?

If yes, can you please build this image? If you don't have time for this, then please just pin the latest dockerfile that you are using in building these images and I'll give it a go.

Btw, one last question, what is the base image for the "latest" image? 

Thanks and sorry for late reply.

**Comment by ukewea** [comment]
Hi Vlad,

Sorry for the late reply, I was preparing for a job interview last week, finally have some spare time for this.

In order to build a python 3.8 version of the image, I'll change the base image to `ubuntu:20.04` (which has python 3.8 built in as a apt package). I'll try to make one in this repo.

The python 3.11 version image (the one with `latest` tag on Docker Hub) uses `ubuntu:23.04` as base image.

**Comment by vsterian** [comment]
Hey!

No worries, hope the interview went well. No need to test this all over again. Finally I have managed to build my base image based on your dockerfile. Thanks a lot for support!

**Comment by ukewea** [comment]
For anyone from future viewing this issue:

Yes, this image DOES work on amd64, arm64, arm/v7.

To prove this, I've made two types of container images and uploaded to GHCR, both contain amd64, arm64, arm/v7 variants:
- an image based on `ubuntu:23.10`, running Python 3.11, with venv ([info
](https://github.com/ukewea/python-talib/pkgs/container/python-talib/189669568?tag=ubuntu23.10-python3.11-20240312), [Dockerfile](https://github.com/ukewea/python-talib/blob/84f9b294609f2a7df4701cbbf5f352025c4e4c08/Dockerfile))
- an image based on `ubuntu:20.04`, running Python 3.8, without venv ([info](https://github.com/ukewea/python-talib/pkgs/container/python-talib/189669890?tag=ubuntu20.04-python3.8-20240312), [Dockerfile](https://github.com/ukewea/python-talib/blob/84f9b294609f2a7df4701cbbf5f352025c4e4c08/Dockerfile-no-venv))

You can reference to the tutorial [here](https://github.com/ukewea/python-talib/issues/2#issuecomment-1961467942) to try them out (by pulling corresponding container image).
